In [1]:
import pandas as pd
import numpy as np
import pickle   
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
EVAL_PICKLE_PATH = "../data/05_reporting/model_evaluation_metrics.pickle/2023-06-06T11.00.15.717Z/model_evaluation_metrics.pickle"

with open(EVAL_PICKLE_PATH, "rb") as f:
    model_evaluation_metrics = pickle.load(f)

In [25]:
model_evaluation_metrics.keys()

dict_keys(['R2 mean', 'R2 std', 'RMSE mean', 'RMSE std', 'MAE mean', 'MAE std', 'MAPE mean', 'MAPE std', 'Max error %', 'Mean median error %', 'Mean error %', 'Mean abs error %', 'Mean % < 5% error', 'Mean % < 10% error', 'final_analysis_df', 'config', 'experiment_name'])

In [26]:
analysis_df = model_evaluation_metrics["final_analysis_df"]

analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6320 entries, 5500 to 901
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Material         6320 non-null   object
 1   Family           6320 non-null   object
 2   Material_info    6320 non-null   object
 3   Dry_or_cond      6320 non-null   object
 4   Manufacturer     6320 non-null   object
 5   Polymer          6320 non-null   object
 6   Fiber_type       6320 non-null   object
 7   Temperature      6320 non-null   float64
 8   Load             6320 non-null   float64
 9   k_fold_test      6320 non-null   int64
 10  R_1000/100       6320 non-null   float64
 11  R_1000/100_pred  6320 non-null   float64
 12  CM_1             4635 non-null   float64
 13  CM_10            6320 non-null   float64
 14  CM_100           6320 non-null   float64
 15  CM_1000          6320 non-null   float64
 16  CM_1000_pred     6320 non-null   float64
 17  +-Rel_error_%    6320 non-null   float64
 18  Rel_error_%      6320 non-null   float64
dtypes: float64(11), int64(1), object(7)
memory usage: 987.5+ KB

In [27]:
analysis_df.head()

,Material,Family,Material_info,Dry_or_cond,Manufacturer,Polymer,Fiber_type,Temperature,Load,k_fold_test,R_1000/100,R_1000/100_pred,CM_1,CM_10,CM_100,CM_1000,CM_1000_pred,+-Rel_error_%,Rel_error_%
5500,Ultramid® B3ZG3,Ultramid®,B3ZG3,dry,BASF,PA6,GF,160.0,8.0,0,0.752827,0.905585,NaN,670.185,580.467,436.991,525.662478,-20.291374,20.291374
5645,Ultramid® T KR 4350,Ultramid®,T KR 4350,dry,BASF,PA6T/6,None,160.0,4.0,0,0.773836,0.910034,NaN,291.715,260.196,201.349,236.787104,-17.600338,17.600338
5501,Ultramid® B3ZG3,Ultramid®,B3ZG3,dry,BASF,PA6,GF,160.0,10.0,0,0.750841,0.882611,NaN,619.617,521.105,391.267,459.933048,-17.549665,17.549665
5646,Ultramid® T KR 4350,Ultramid®,T KR 4350,dry,BASF,PA6T/6,None,160.0,5.0,0,0.755442,0.884783,NaN,273.958,235.216,177.692,208.115062,-17.121233,17.121233
5497,Ultramid® B3ZG3,Ultramid®,B3ZG3,dry,BASF,PA6,GF,160.0,2.0,0,0.803258,0.936994,NaN,770.670,732.950,588.748,686.769488,-16.649142,16.649142

In [28]:
analysis_df.k_fold_test.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Sort by last column

analysis_df.sort_values(by=analysis_df.columns[-1], ascending=False)

,Material,Family,Material_info,Dry_or_cond,Manufacturer,Polymer,Fiber_type,Temperature,Load,k_fold_test,R_1000/100,R_1000/100_pred,CM_1,CM_10,CM_100,CM_1000,CM_1000_pred,+-Rel_error_%,Rel_error_%
964,FORTRON® 1140L4,FORTRON®,1140L4,dry,Celanese,PPS,GF,150.0,5.0,8,0.516695,0.838508,15966.00,15369.20,13035.30,6735.28,10930.206077,-62.282876,62.282876
268,Arnite® AV2 372,Arnite®,AV2 372,dry,DSM Engineering Materials,PET,GF,23.0,20.0,7,0.632459,0.966960,17250.70,16418.90,16139.70,10207.70,15606.436522,-52.888864,52.888864
263,Arnite® AV2 370 XT,Arnite®,AV2 370 XT,dry,DSM Engineering Materials,PET,GF,23.0,20.0,7,0.632459,0.966960,17250.70,16418.90,16139.70,10207.70,15606.436522,-52.888864,52.888864
258,Arnite® AV2 370 B,Arnite®,AV2 370 B,dry,DSM Engineering Materials,PET,GF,23.0,20.0,7,0.632459,0.966960,17250.70,16418.90,16139.70,10207.70,15606.436522,-52.888864,52.888864
965,FORTRON® 1140L4,FORTRON®,1140L4,dry,Celanese,PPS,GF,150.0,10.0,8,0.552814,0.818561,13845.80,12874.30,10535.30,5824.06,8623.787534,-48.071750,48.071750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2778,Makrolon® 9425,Makrolon®,9425,dry,Covestro Deutschland AG,PC,None,23.0,60.0,1,0.923077,0.923106,5128.21,4878.05,4545.45,4195.80,4195.930567,-0.003112,0.003112
3716,Ultradur® B 4300 G10,Ultradur®,B 4300 G10,dry,BASF,PBT,GF,120.0,48.0,2,0.927466,0.927495,3377.38,3155.38,2937.11,2724.07,2724.153806,-0.003076,0.003076
166,Apec® 1745,Apec®,1745,dry,Covestro Deutschland AG,PC,None,23.0,20.0,4,0.931037,0.931021,2057.61,1960.78,1851.85,1724.14,1724.111791,0.001636,0.001636
228,Apec® DP1-9354,Apec®,DP1-9354,dry,Covestro Deutschland AG,PC,None,23.0,20.0,4,0.931037,0.931021,2057.61,1960.78,1851.85,1724.14,1724.111791,0.001636,0.001636
197,Apec® 1803,Apec®,1803,dry,Covestro Deutschland AG,PC,None,23.0,20.0,4,0.931037,0.931021,2057.61,1960.78,1851.85,1724.14,1724.111791,0.001636,0.001636

In [47]:
# groupby "Family" and "k_fold_test"
analysis_df.groupby(["Family", "k_fold_test"]).count()

,,Material,Material_info,Dry_or_cond,Manufacturer,Polymer,Fiber_type,Temperature,Load,R_1000/100,R_1000/100_pred,CM_1,CM_10,CM_100,CM_1000,CM_1000_pred,+-Rel_error_%,Rel_error_%
Family,k_fold_test,,,,,,,,,,,,,,,,,
Akulon®,8,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158
Apec®,4,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90
Arnite®,7,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Bayblend®,4,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
CELANEX®,8,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
CELCON®,5,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
CELSTRAN®,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Crastin®,7,202,202,202,202,202,202,202,202,202,202,191,202,202,202,202,202,202
Delrin®,9,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Durethan,5,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295
Elastollan®,9,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
FORTRON®,8,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Grilamid,7,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
Grilon,9,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159
Grivory,8,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189
HOSTAFORM®,5,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
Hytrel®,9,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187
IMPET®,5,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Luran®,4,304,304,304,304,304,304,304,304,304,304,0,304,304,304,304,304,304
Makrolon®,1,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947
Minlon®,3,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Novodur®,6,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
Orgalloy®,3,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
PLEXIGLAS®,9,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71
Pebax®,4,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
Pocan,7,143,143,143,143,143,143,143,143,143,143,142,143,143,143,143,143,143
Rilsamid®,8,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
Rilsan®,6,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63
Rynite®,4,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Stanyl®,6,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137
Styrolution®,5,33,33,33,33,33,33,33,33,33,33,0,33,33,33,33,33,33
Styrolux®,4,27,27,27,27,27,27,27,27,27,27,0,27,27,27,27,27,27
TROGAMID®,6,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Terblend®,7,23,23,23,23,23,23,23,23,23,23,0,23,23,23,23,23,23
Terluran®,9,23,23,23,23,23,23,23,23,23,23,0,23,23,23,23,23,23
Terlux®,6,19,19,19,19,19,19,19,19,19,19,0,19,19,19,19,19,19
Ultradur®,2,583,583,583,583,583,583,583,583,583,583,286,583,583,583,583,583,583
Ultraform®,6,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249
Ultramid®,0,1213,1213,1213,1213,1213,1213,1213,1213,1213,1213,283,1213,1213,1213,1213,1213,1213
Ultrason®,5,91,91,91,91,91,91,91,91,91,91,85,91,91,91,91,91,91
VESTAKEEP®,7,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
VESTAMID®,7,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
VESTODUR®,8,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Zytel®,3,447,447,447,447,447,447,447,447,447,447,436,447,447,447,447,447,447

In [53]:
analysis_df.groupby(["Family", "k_fold_test"]).count().sort_values(by="Material")

,,Material,Material_info,Dry_or_cond,Manufacturer,Polymer,Fiber_type,Temperature,Load,R_1000/100,R_1000/100_pred,CM_1,CM_10,CM_100,CM_1000,CM_1000_pred,+-Rel_error_%,Rel_error_%
Family,k_fold_test,,,,,,,,,,,,,,,,,
VESTAKEEP®,7,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
CELSTRAN®,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
TROGAMID®,6,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Rynite®,4,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
CELCON®,5,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Delrin®,9,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
VESTODUR®,8,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Orgalloy®,3,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
Arnite®,7,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Terlux®,6,19,19,19,19,19,19,19,19,19,19,0,19,19,19,19,19,19
IMPET®,5,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Bayblend®,4,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Terluran®,9,23,23,23,23,23,23,23,23,23,23,0,23,23,23,23,23,23
Rilsamid®,8,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
Terblend®,7,23,23,23,23,23,23,23,23,23,23,0,23,23,23,23,23,23
Styrolux®,4,27,27,27,27,27,27,27,27,27,27,0,27,27,27,27,27,27
Styrolution®,5,33,33,33,33,33,33,33,33,33,33,0,33,33,33,33,33,33
Novodur®,6,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
Minlon®,3,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Grilamid,7,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
Elastollan®,9,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
FORTRON®,8,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Pebax®,4,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
Rilsan®,6,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63
HOSTAFORM®,5,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
CELANEX®,8,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
PLEXIGLAS®,9,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71
VESTAMID®,7,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
Apec®,4,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90
Ultrason®,5,91,91,91,91,91,91,91,91,91,91,85,91,91,91,91,91,91
Stanyl®,6,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137
Pocan,7,143,143,143,143,143,143,143,143,143,143,142,143,143,143,143,143,143
Akulon®,8,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158
Grilon,9,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159,159
Hytrel®,9,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187,187
Grivory,8,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189,189
Crastin®,7,202,202,202,202,202,202,202,202,202,202,191,202,202,202,202,202,202
Ultraform®,6,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249,249
Durethan,5,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295,295
Luran®,4,304,304,304,304,304,304,304,304,304,304,0,304,304,304,304,304,304
Zytel®,3,447,447,447,447,447,447,447,447,447,447,436,447,447,447,447,447,447
Ultradur®,2,583,583,583,583,583,583,583,583,583,583,286,583,583,583,583,583,583
Makrolon®,1,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947,947
Ultramid®,0,1213,1213,1213,1213,1213,1213,1213,1213,1213,1213,283,1213,1213,1213,1213,1213,1213

In [38]:
data_df = pd.read_parquet('/home/hector/Github/creep-prediction/data/03_model_input/engineered_model_data.pq')
data_df

        CM_100  R_100/10  Temperature  Load     CM_10   Family  R_1000/100
0      645.161  0.838709         23.0   2.0   769.231  Akulon®    0.837839
1      597.015  0.850747         23.0   4.0   701.754  Akulon®    0.858973
2      535.714  0.866071         23.0   6.0   618.557  Akulon®    0.861538
3      484.848  0.848483         23.0   8.0   571.429  Akulon®    0.863875
4      429.765  0.840166         23.0  10.0   511.524  Akulon®    0.859149
...        ...       ...          ...   ...       ...      ...         ...
6356  1734.100  0.878613        200.0  30.0  1973.680   Zytel®    0.848042
6357  6480.650  0.995140        110.0  20.0  6512.300   Zytel®    0.941524
6358  5769.230  0.988461        110.0  30.0  5836.580   Zytel®    0.945455
6359  5060.890  0.981813        110.0  40.0  5154.640   Zytel®    0.949398
6360  4566.210  0.977168        110.0  50.0  4672.900   Zytel®    0.952175

[6320 rows x 7 columns]

In [39]:
data_df.groupby("Family").count()

              CM_100  R_100/10  Temperature  Load  CM_10  R_1000/100
Family
Akulon®          158       158          158   158    158         158
Apec®             90        90           90    90     90          90
Arnite®           19        19           19    19     19          19
Bayblend®         21        21           21    21     21          21
CELANEX®          66        66           66    66     66          66
CELCON®           14        14           14    14     14          14
CELSTRAN®          4         4            4     4      4           4
Crastin®         202       202          202   202    202         202
Delrin®           16        16           16    16     16          16
Durethan         295       295          295   295    295         295
Elastollan®       52        52           52    52     52          52
FORTRON®          53        53           53    53     53          53
Grilamid          43        43           43    43     43          43
Grilon           159       159          159   159    159         159
Grivory          189       189          189   189    189         189
HOSTAFORM®        64        64           64    64     64          64
Hytrel®          187       187          187   187    187         187
IMPET®            20        20           20    20     20          20
Luran®           304       304          304   304    304         304
Makrolon®        947       947          947   947    947         947
Minlon®           40        40           40    40     40          40
Novodur®          36        36           36    36     36          36
Orgalloy®         18        18           18    18     18          18
PLEXIGLAS®        71        71           71    71     71          71
Pebax®            62        62           62    62     62          62
Pocan            143       143          143   143    143         143
Rilsamid®         23        23           23    23     23          23
Rilsan®           63        63           63    63     63          63
Rynite®           12        12           12    12     12          12
Stanyl®          137       137          137   137    137         137
Styrolution®      33        33           33    33     33          33
Styrolux®         27        27           27    27     27          27
TROGAMID®          9         9            9     9      9           9
Terblend®         23        23           23    23     23          23
Terluran®         23        23           23    23     23          23
Terlux®           19        19           19    19     19          19
Ultradur®        583       583          583   583    583         583
Ultraform®       249       249          249   249    249         249
Ultramid®       1213      1213         1213  1213   1213        1213
Ultrason®         91        91           91    91     91          91
VESTAKEEP®         3         3            3     3      3           3
VESTAMID®         75        75           75    75     75          75
VESTODUR®         17        17           17    17     17          17
Zytel®           447       447          447   447    447         447